project/axf/urls.py
from django.urls import path, re_path
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    re_path(r'^test/$', views.testpage, name='test'),
    re_path(r'^$', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    re_path(r'^mall/(\d+)/(\d+)/(\d+)/$', views.mall, name='mall'),
    re_path(r'^mall/$', views.mall_redirect, name='mall_redirect'),
    re_path(r'^trolley/$', views.trolley, name='trolley'),
    re_path(r'^profile/$', views.profile, name='profile'),
    # 登录、注册
    re_path(r'^login/$', views.login, name='login'),
    re_path(r'^register/$', views.register, name='register'),
    # 检查用户注册id是否已存在
    re_path(r'^checkuserid/$', views.checkuserid, name='checkuserid'),
    re_path(r'^logout/$', views.logout, name='logout'),
    re_path(r'^signout/$', views.signout, name='signout'),
    # 修改购物车信息
    re_path(r'^changetrolley/(\d+)/$', views.changetrolley, name='changetrolley'),
    # 提交订单
    re_path(r'^submitorder/$', views.submitorder, name='submitorder'),
    # 验证码
    re_path(r'^captcha/$', views.captcha, name='captcha'),
]

# 实现登录、注册或进入个人资料时展示头像
urlpatterns += static('/login/', document_root=settings.MEDIA_ROOT)
urlpatterns += static('/profile/', document_root=settings.MEDIA_ROOT)
urlpatterns += static('/register/', document_root=settings.MEDIA_ROOT)


# 测试页
urlpatterns += static('/test/', document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include(("axf.urls", 'axf'), namespace='axf')),
]

project/axf/forms/login.py
from django import forms


#  define login forms Class here


class LoginForm(forms.Form):
    '''required=True表示必填, TextInput和Textarea可以实现相同的功能;
    # 其中attrs为指定对应字段的前端样式，相当于html表单中的class指定样式'''
    username = forms.CharField(max_length=12, min_length=6, required=True,
                               error_messages={"required": "账号不能为空", "invalid": "格式错误"},
                               widget=forms.TextInput(attrs={"class": "un", "placeholder": "账号长度为6到12个字符"}))
    '''PasswordInput是密文输入'''
    password = forms.CharField(max_length=16, min_length=6, required=True,
                               widget=forms.PasswordInput(attrs={"class": "pw", "placeholder": "密码长度至少为6"}))

project/axf/forms/register.py
from django import forms


#  define register forms Class here


class RegisterForm(forms.Form):
    '''required=True表示必填; 文本输入TextInput和Textarea可以实现相同的功能;
    # 其中attrs为指定对应字段的前端样式，相当于html表单中的class指定样式'''
    # 注意attrs样式中的name一定是下面的变量命名，重新在attrs中对name命名是无效的
    username = forms.CharField(max_length=12, min_length=6, required=True,
                               error_messages={"required": "账号不能为空", "invalid": "格式错误"},
                               widget=forms.PasswordInput(attrs={"id": "account", "type": "text",
                                                                 "class": "form-control",
                                                                 "placeholder": "账号长度为6到12个字符",
                                                                 "aria-describedby": "basic-addon1", }))
                                                        # "name": "userAccount"})) # 在这里定义的name无效，name仍会是username

    password = forms.CharField(max_length=16, min_length=6, required=True,
                               widget=forms.PasswordInput(attrs={"id": "pass", "type": "password",
                                                                 "class": "form-control",
                                                                 "placeholder": "密码长度为6~16个字符",
                                                                 "aria-describedby": "basic-addon1",}))

    password_confirm = forms.CharField(max_length=16, min_length=6, required=True,
                                       widget=forms.PasswordInput(attrs={"id": "password", "type": "password",
                                                                         "class": "form-control",
                                                                         "placeholder": "密码长度为6~16个字符",
                                                                         "aria-describedby": "basic-addon1",}))
    # ...其他注册栏位可根据实际需求再添加

project/axf/views.py
import os, random, time, string, io
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Wheel, Navigator, MustBuy, Commodity, GoodsOnSale, GoodsTypes, Goods, User, Trolley, Order
# from project import settings  # 效果同下一条
from django.conf import settings
from .forms.login import LoginForm
from .forms.register import RegisterForm
from PIL import Image, ImageDraw, ImageFont
from django.template.defaulttags import register


# 测试页
def testpage(request):
    verify_msg = ''
    if request.POST:
        _captcha_submit = request.POST.get('verify_code').lower()
        # 注意这里提交的验证码需要小写，服务器的验证码生成时已经小写，这样分开做是为了避免当验证码过期了再使用lower()函数而报错
        _captcha_server = request.session.get('verify_code')
        if _captcha_server == _captcha_submit:
            verify_msg = '验证成功'
        else:
            verify_msg = '验证失败'
    return render(request, 'axf/test.html', {"msg": verify_msg})


# 重定义字典方法，方便模板中使用字典
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


# 主页
def home(request):
    in_home = True
    wheelsList = Wheel.objects.all()
    navList = Navigator.objects.all()
    mustBuyList = MustBuy.objects.all()
    commodityList = Commodity.objects.all()
    commodity1 = commodityList[0]
    commodity2 = commodityList[1:3]
    commodity3 = commodityList[3:7]
    commodity4 = commodityList[7:11]
    mainList = GoodsOnSale.objects.all()
    return render(request, 'axf/home.html', {"title": "主页", "wheelsList": wheelsList, "navList": navList,
                                             "mustBuyList": mustBuyList, 'commodity1': commodity1,
                                             'commodity2': commodity2, 'commodity3': commodity3,
                                             'commodity4': commodity4, "mainList": mainList,
                                             "in_home": in_home})


# 个人资料
def profile(request):
    in_profile = True
    print("进入profile验证userToken", request.session.get('userToken'))
    # 尝试获取用户登录信息
    try:
        # 从服务器获取对应的user信息，自动登录
        token = request.session.get('userToken')
        user = User.objects.get(userToken=token)
        userName = user.userName
        userLevel = user.userLevel
        userProfile = user.userAccount + user.userImg
        # print(userProfile)
        return render(request, 'axf/profile.html', {"title": "我的", "userName": userName, "userLevel": userLevel,
                                                    'userProfile': userProfile, "in_profile": in_profile})
    except User.DoesNotExist as e:
        return render(request, 'axf/profile.html', {"title": "我的", "in_profile": in_profile})


# 登录
def login(request):
    err_msg = ''
    # 判断是否提交POST进行登录
    if request.method == 'POST':
        f = LoginForm(request.POST)
        if f.is_valid():
            user = f.cleaned_data["username"]
            password = f.cleaned_data["password"]
            # 验证码进行比对，服务端的验证码小写化在存入session时已执行过
            captcha_submit = request.POST.get('verify_code').lower()
            captcha_server = request.session.get('verify_code')
            print(captcha_submit, captcha_server)
            if captcha_server == captcha_submit:
                try:
                    getuser = User.objects.get(userAccount=user, userPassword=password)
                    userName = getuser.userName
                    userLevel = getuser.userLevel
                    userProfile = getuser.userAccount + getuser.userImg
                    print("获取用户头像文件路径：", userProfile)
                    # 创建本次登录的userToken，并保存到数据库
                    userToken = ''.join(random.sample(string.ascii_letters + string.digits, 8)) + \
                                time.strftime("%H%M%S", time.localtime())
                    getuser.userToken = userToken
                    getuser.save()
                    # 创建session中token，设置过期时间
                    request.session["userToken"] = userToken
                    # 关闭浏览器账号就过期（0）或其他时间（秒），或者时间对象
                    request.session.set_expiry(0)
                    return render(request, 'axf/profile.html', {"userName": userName, "userLevel": userLevel,
                                                                "userProfile": userProfile})
                except User.DoesNotExist as e:
                    err_msg = '账号或密码错误'
            else:
                err_msg = '验证码错误'
    # 点击未登录，加载登录表单
    f = LoginForm()
    print("未登录时走这里登录", err_msg)
    return render(request, 'axf/login.html', {"title": "登录", "form": f, 'error': err_msg})


#  生成验证码，可直接使用HttpResponse返回到html中，然后在img引用生成的验证码，实现及时性
def captcha(request):
    # 定义背景颜色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), random.randrange(20, 100))
    width = 100
    height = 50
    # 创建画布
    img = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(img)
    # 调用画笔的point()函数绘制验证码的干扰点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), random.randrange(0, 255), 55)
        draw.point(xy, fill=fill)
    # 定义验证码的备选值————取所有字母和数字的组合
    _str = string.digits + string.ascii_letters
    # 随机在其中取四个值作为验证码
    rand_codes = ''.join(random.sample(_str, 4))
    # 定义字体大小
    size = int(min(width / len(rand_codes), height))
    # 构造字体对象
    font = ImageFont.truetype(r'http://moelimoe.fun/wp-content/uploads/2020/%E5%AD%97%E4%BD%93/arial/arial.ttf', size)
    # 构造字体颜色,四个字颜色不同
    for i in range(4):
        fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
        draw.text((i * 25, 2), rand_codes[i], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    # # 将验证码缓存入session，后面做进一步验证，注意应该在这里存入的时候变为小写，
    # 否则验证码过期就变成了空，再进行lower()操作会抛出异常
    request.session['verify_code'] = rand_codes.lower()
    # 设置验证码有效时间(秒)
    request.session.set_expiry(60)
    # BytesIO()可以实现在内存中读写bytes
    buf = io.BytesIO()
    img.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，在html的img中引用src="/captcha/"即可
    return HttpResponse(buf.getvalue(), 'image/jpg')
    # png也行
    # return HttpResponse(buf.getvalue(), 'png')


# 登出1
# 1、退出登录使用logout(request)，函数需使用不同的名字
# 注意：如果函数命名为logout()则会和登出函数logout()重名，会导致冲突返回错误Maximum recursion depth exceeded
def signout(request):
    logout(request)
    return redirect('/profile/')


# 登出2
# 使用clear()清除session实现登出
def logout(request):
    request.session.clear()
    return render(request, 'axf/profile.html')


# 注册
def register(request):
    get_registered = ''
    if request.POST:
        f = RegisterForm(request.POST)
        if f.is_valid():
            try:
                userAccount = request.POST.get('username')  # name为"username"，再register.py中RegisterForm里
                userPassword = request.POST.get('password')  # 同上
                userName = request.POST.get('userName')
                userPhone = request.POST.get('userPhone')
                userAddress = request.POST.get('userAddress')
                userLevel = 0
                # 生成token值注册成功就会自动登录
                userToken = ''.join(random.sample(string.ascii_letters + string.digits, 8)) + \
                            time.strftime("%H%M%S", time.localtime())
                userImg = request.FILES['userImg']
                request.session['userToken'] = userToken
                # 使用用户的账户拼接，以确保文件名不重复
                filePath = os.path.join(settings.MEDIA_ROOT, userAccount + userImg.name)
                with open(filePath, 'wb') as fp:
                    # for info in userImg.chunk():
                    for info in userImg:
                        fp.write(info)
                userRegister = User.createuser(userAccount, userPassword, userName, userPhone,
                                               userAddress, userImg, userLevel, userToken)
                userRegister.save()
                # 注册成功就导航到profile登录
                return redirect('/profile/')
            except Exception as e:
                get_registered = "注册失败，请检查你填写的信息是否正确"
                print("表单验证失败，错误信息：", e)
    # 未提交POST信息，刚进入页面则get_registered为空，否则提示注册失败
    f = RegisterForm()
    return render(request, 'axf/register.html', {"title": "注册", "form": f, 'get_registered': get_registered})


# 检测注册账户是否已存在，返回Json响应提示并阻断用户提交注册
def checkuserid(request):
    userid = request.POST.get("userid")
    try:
        user = User.objects.get(userAccount=userid)
        return JsonResponse({"data": "该用户名已被注册", "status": "error"})
    except User.DoesNotExist as e:
        return JsonResponse({"data": "注册成功", "status": "success"})


# 商城
def mall(request, categoryid, cid, sortid):
    '''categoryid为产品大分类；cid为产品小分类，用于查询；sortid为排序id；'''
    in_mall = True
    order_dict = {'0': "综合排序", '1': "销量排序", '2': "价格最低", '3': "价格最高"}

    leftBar = GoodsTypes.objects.all()
    # 展示mall页面所有商品信息
    if cid == '0':
        productList = Goods.objects.filter(categoryid=categoryid)
    else:
        productList = Goods.objects.filter(categoryid=categoryid, childId=cid)  # 两个条件同时满足
    group = leftBar.get(typeid=categoryid)
    # 分割数据：全部分类:0#进口水果:103534#国产水果:103533
    # 定义闪购页面上方分类功能
    childList = []
    childtypes = group.childtypenames.split("#")
    for s in childtypes:
        arr = s.split(":")
        obj = {"childName": arr[0], "childId": arr[1]}
        childList.append(obj)
    # 定义闪购页面排序功能，排序使用order_by()
    if sortid == '1':
        productList = productList.order_by('productnum')

    elif sortid == '2':
        productList = productList.order_by('price')
    elif sortid == '3':
        productList = productList.order_by('-price')
    token = request.session.get("userToken")  # token是userToken
    # （如果已登录）取出用户购物车对应商品的数量，加载到mall页面
    item_info_Trolley = {}  # 储存用户购物车的物品
    if token:
        user = User.objects.get(userToken=token)
        user_Trolley = Trolley.objects.filter(userAccount=user.userAccount)  # 获取用户的trolley，而后返回其productnum作为默认值显示在mall页面
        for item in user_Trolley:

project/templates/axf/base.html
<!DOCTYPE html>
{% load static from staticfiles%}
<!--{% load staticfiles%}-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>




</head>
<body>
    <header>
        <h4><b>header</b></h4>
    </header>
    <div>
        {% block base %}
        {% endblock base %}
    </div>
    <footer>
        <!--                span存放图片，实现语句在base.css -->
        <a href="/home/" class="home">
            <dl>
                <dt><span></span></dt>
                <dd>主页</dd>
            </dl>
        </a>
<!--        数字实现进入商城页面，自动显示热销榜-->
<!--        使用反向解析-->
        <a href="{% url 'axf:mall' 104749 0 0 %} " class="mall">
            <dl>
                <dt><span></span></dt>
                <dd>闪购商城</dd>
            </dl>
        </a>
        <a href="/trolley/" class="trolley">
            <dl>
                <dt><span></span></dt>
                <dd>购物车</dd>
            </dl>
        </a>

        <a href="/profile/" class="profile">
            <dl>
                <dt><span></span></dt>
                <dd>我的</dd>
            </dl>
        </a>
    </footer>

    <!--    实现移动端页面-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">

    <link rel="stylesheet" type="text/css" href="{% static 'main/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/swiper.min.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/reset.css'%}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/base.css'%}" />

    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/swiper.min.js' %}"></script>
    <script type="text/javascript" charset="utf-8" src="{% static 'main/js/base.js' %}"></script>

    <!--    针对不同的页面使用的样式不同，写一个block由它们在自己页面定义 -->
    {% block linkscript %}
    {% endblock linkscript %}
</body>
</html>

project/templates/axf/home.html
{% extends 'axf/base.html'%}
{% load static from staticfiles%}

<!--用于当css和js需要单独定义时使用-->
{% block linkscript %}
<link rel="stylesheet" type="text/css" href="{% static 'home/css/home.css'%}" />
<script type="text/javascript" charset="utf-8" src="{% static 'home/js/home.js' %}"></script>
{% endblock linkscript %}

{% block base%}
<h4><b>主页</b></h4>
<div id="home">
    {# 区域一，轮播墙 #}
    {# swiper-container、swiper-slide由main下的swiper.min.css控制 #}
    <section class="swiper-container" id="topSwiper">
        {# 轮播墙，一张图一个墙 #}
        <div class="swiper-wrapper">
            {% for item in wheelsList %}
                <div class="swiper-slide">
                    <a href="/mall/{{item.track_id}}/0/0/"><img src="{{item.img}}"/> </a>
                </div>
            {% endfor %}
        </div>
        {# 轮播图下方控制原点，但点击圆点并没有作用 #}
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
    </section>

    {# 编写第二栏导航菜单区域 #}
    <section class="navMenu">
        <nav>
            <ul>
                {% for item in navList%}
                <li>
                    <a href="#">
                        <img src="{{item.img}}"/>
                        <span>{{item.name}}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </nav>

        {# 第三个区域放在第二个div，归属于菜单，它其实也是一个轮播墙，与第一个区域差不多，下方没有控制小圆点 #}
        <menu class="swiper-container" id="swiperMenu">
            {# 样式是li类 #}
            <ul class="swiper-wrapper">
                {% for item in mustBuyList %}
                    <li class="swiper-slide">
                        <a href="#"><img src="{{item.img}}"/></a>
                    </li>
                {% endfor %}
            </ul>
        </menu>
    </section>


    {# 第四个区域，分为三部分 #}
    <section class="commodity">
        {# part1 #}
        <h2 href="/mall/{{item.categoryid}}/0/0/"><img src="{{commodity1.img}}" alt="鲜峰速递"/></h2>

        {# part2 #}
        <fieldset>
            {% for item in commodity2%}
                <a href="/mall/{{item.categoryid}}/0/0/"><img src="{{item.img}}" alt="商品区域2"/></a>
            {% endfor%}
        </fieldset>

        {# part3 #}
        <ul>
            {% for item in commodity3 %}
            <li>
                <a href="/mall/{{item.categoryid}}/0/0/">
                    <img src="{{item.img}}" alt="商品区域3"/>
                    <span>{{item.name}}</span>
                </a>

            </li>
            {% endfor %}
        </ul>

        {# part4 #}
        <ol>
            {% for item in commodity4 %}
            <li>
                <a href="/mall/{{item.categoryid}}/0/0/">
                    <img src="{{item.img}}" alt="商品区域4"/>
                </a>
            </li>
            {% endfor %}
        </ol>
    </section>

<!--     主要商品区域 -->
    <section class="mainInfo">
        {% for item in mainList%}
        <section>
            <h3>
                {{item.name}}
                <a class="moreinfo" href="/mall/{{item.categoryid}}/0/0/">更多></a>
                <span></span>
            </h3>
            <div>
                <a href="#"><img id="img0" src="{{item.img}}" alt="item.name"/></a>
            </div>
            <ul>
                <li>
                    <a href="#">
                        <img class="sub-img" src="{{item.img1}}"/>
                        <span class="description">{{item.longname1}}</span>
                        <span>¥{{item.price1}}</span>
                        <s>¥{{item.marketprice1}}</s>
                    </a>
                    <button><span>&#43;</span></button>
                </li>
                <li>
                    <a href="#">
                        <img class="sub-img" src="{{item.img2}}"/>
                        <span class="description">{{item.longname2}}</span>
                        <span>¥{{item.price2}}</span>
                        <s>¥{{item.marketprice2}}</s>
                    </a>
                    <button><span>&#43;</span></button>
                </li>
                <li>
                    <a href="#">
                        <img class="sub-img" src="{{item.img3}}"/>
                        <span class="description">{{item.longname3}}</span>
                        <span>¥{{item.price3}}</span>
                        <s>¥{{item.marketprice3}}</s>
                    </a>
                    <button><span>&#43;</span></button>
                </li>
            </ul>
        </section>
        {% endfor %}
    </section>

</div>

<!--footer图标变色-->
{% if in_home %}
<a href="/home/" class="home">
    <dl>
        <dt><span></span></dt>
        <dd>主页</dd>
    </dl>
</a>
{% endif %}

{% endblock base%}

project/templates/axf/login.html
{% extends 'axf/base.html' %}
{% load static from staticfiles %}
{% block linkscript%}
<link rel="stylesheet" type="text/css" href="{% static 'profile/css/login.css' %}" />
<script type="text/javascript" charset="utf-8" src="{% static 'profile/js/login.js' %}" ></script>
{% endblock linkscript%}


{% block base %}
<div id="login">
    <a href="/profile/"><p>&lt;返回我的</p></a>
    <span>{{err_msg}}</span>
    <div id="box">
        <form action="/login/" method="post">
            {% csrf_token %}
            <div class="input-group">
                账号：{{form.username}}
                <br />
                {% if error.username.0 %}
                <span>{{error.username.0}}</span>
                {% endif %}
            </div>
            <div class="input-group">
                密码：{{form.password}}
                <br />
                {% if error.password.0 %}
                <span>{{error.password.0}}</span>
                {% endif %}
            </div>
            <div>
                <img src="/captcha/" alt="验证码"/>
                <br/>
                <label>
                    <input class="form-control" type="text" name="verify_code" placeholder="请输入四位数验证码"/>
                    <input type="hidden" name="verify_code_key" value="{{ filename }}"/>
                </label>
            </div>
            <div>
                <span style="color: red">{{ error }}</span>
                <br>
                <input type="submit" value="登陆"/>
                <a href="/register/">没有账号？点我注册</a>
            </div>
        </form>
    </div>
</div>
{% endblock base %}

project/templates/axf/mall.html
{% extends 'axf/base.html'%}
{% load static from staticfiles%}

{% block linkscript %}
<!--用于当css和js需要单独定义时使用-->
<link rel="stylesheet" type="text/css" href="{% static 'mall/css/mall.css'%}" />
<script type="text/javascript" charset="utf-8" src="{% static 'mall/js/mall.js' %}"></script>
{% endblock linkscript %}

{% block base%}
<h4><b>商城</b></h4>
<div id="mall">
    <aside>
        <!-- 闪购商城左侧导航栏 -->
        <menu>
            <ul>
                {% for item in leftBar %}
                <li>
                    <span class="yellowSlide"></span>
<!--                    传到指定id的页面，typeid导向对应分类的商品页 -->
                    {# <a href="/mall/{{item.typeid}}/0">{{item.typename}}</a>可以改成如下方式#}
                    {% if categoryid == item.typeid%}
                    <a href="{% url 'axf:mall' item.typeid 0 0 %}" style="color: #761c19">{{item.typename}}</a>
                    {% else %}
                    <a href="{% url 'axf:mall' item.typeid 0 0 %}">{{item.typename}}</a>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </menu>
    </aside>


    <!--   字体，直接引用即可 -->
    <section>
        <nav>
            <ul>
                <li><span id="alltypebtn">全部类型<span class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span></span></li>
                <li><span id="showsortbtn">综合排序<span class="glyphicon glyphicon-chevron-down" style="font-weight: 100"></span></span></li>
            </ul>
        </nav>


        <!--        商品展示菜单  -->
        <menu>
            <ul>
                {% for item in productList %}
                <li>
                    <a href="#">
                        <img src="{{item.productimg}}" />
                        <article class="shoppingInfo">
                            <h6>{{item.productlongname}}</h6>
<!--                            精选标签，可根据实际情况修改-->
                            <p class="detailTag"><span>精选</span><span>{{item.pedesc}}</span></p>
<!--                            规格-->
                            <span class="unit">{{item.specifics}}</span>
<!--                            价格-->
                            <p class="price"><span>￥{{item.price}}</span><s><span>￥{{item.marketprice}}</span></s></p>
                        </article>
                    </a>
<!--                    商品加一/减一-->
                    <section>
<!--                        商品大于0才显示减号-->
                        {# {% if item.num > 0 %} #}
                            <button ga="{{item.productid}}" class="subShopping">-</button>
                        {#   {% endif %} #}
                        {% if item.productid in item_info_Trolley.keys %}
                            <span id="{{item.productid}}">{{ item_info_Trolley|get_item:item.productid }}</span>
                        {% else %}
                            <span id="{{item.productid}}">0</span>
                        {% endif %}
                        <button ga="{{item.productid}}" class="addShopping">+</button>
                    </section>
                </li>
                {% endfor %}
            </ul>
            <div id="typediv">
                <div>
                    {% for item in childList %}
            <!--              categoryid用于产品分类，换成反向解析         -->
                        {# <a href="/market/{{categoryid}}/{{item.childId}}/0/"><span>{{item.childName}}</span></a> #}
                        <a href="{% url 'axf:mall' categoryid item.childId 0 %}"><span>{{item.childName}}</span></a>
                    {% endfor %}
                </div>
            </div>

<!--            排序 -->
            <div id="sortdiv">
                <div>
<!--                    <a href=" {% url 'axf:mall' categoryid cid 0 %}" class="sorta"><span>综合排序</span></a>-->
<!--                    <a href=" {% url 'axf:mall' categoryid cid 1 %}" class="sorta"><span>销量排序</span></a>-->
<!--                    <a href=" {% url 'axf:mall' categoryid cid 2 %}" class="sorta"><span>价格最低</span></a>-->
<!--                    <a href=" {% url 'axf:mall' categoryid cid 3 %}" class="sorta"><span>价格最高</span></a>-->
                    {% for order in order_dict %}
                    <a href=" {% url 'axf:mall' categoryid cid order %}" class="sorta"><span>{{order_dict|get_item:order}}</span></a>
                    {% endfor %}

                </div>
            </div>
        </menu>
    </section>
</div>

<!--footer图标变色-->
{% if in_mall %}
<a href="/mall/" class="mall">
    <dl>
        <dt><span></span></dt>
        <dd>闪购商城</dd>
    </dl>
</a>
{% endif %}
{% endblock base%}

project/templates/axf/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试页面</title>
</head>
<body>
    <form action="/test/" method="post">
        <img src="/captcha/" alt="验证码"/>
        <div>
            <label>
                <input type="text" name="verify_code" placeholder="请输入图片中验证码">
            </label>
            <input type="submit" value="验证"/>
        </div>
    </form>
    <a>验证结果：</a>
    <p style="color: red">{{msg}}</p>
    <p>{{ s1 }}</p>
</body>
</html>

project/templates/axf/verifycode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <img src="temp.png"/>
</body>
</html>